theme: jekyll-theme-slate
title: Jogja Smart Tour
description: Jogja Smart Tour adalah platform perencanaan wisata cerdas yang dirancang untuk membantu wisatawan merencanakan perjalanan mereka di Yogyakarta dengan lebih efisien, personal, dan terstruktur. Dengan teknologi kecerdasan buatan dan komputasi awan, aplikasi ini menyediakan rekomendasi destinasi yang dipersonalisasi, itinerary otomatis, serta estimasi biaya perjalanan yang akurat. 
